name: 🏁 Windows Builds
on: [workflow_dispatch]

# Global Settings
# SCONS_CACHE for windows must be set in the build environment
env:
  GODOT_BASE_BRANCH: 3.x
  SCONSFLAGS: platform=windows verbose=yes warnings=all werror=yes debug_symbols=no --jobs=2
  SCONS_CACHE_MSVC_CONFIG: true
  SCONS_CACHE_LIMIT: 4096


jobs:
  windows-editor:
    # Windows 10 with latest image
    runs-on: "windows-latest"

    # Windows Editor - checkout with the plugin
    name: Editor (target=release_debug, tools=yes)

    steps:
    - name: Make dir
      run: |
       mkdir godot
       mkdir godot/modules/qurobullet
       
    - name: clone godot
      uses: actions/checkout@v2
      with:
        repository: godotengine/godot
        path: godot
        ref: 3.3.2-stable
    

    - name: Load .scons_cache directory
      id: windows-editor-cache
      uses: RevoluPowered/cache@v2.1
      with:
        path: ${{github.workspace}}/.scons_cache/
        key: ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
        restore-keys: |
          ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
          ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}
          ${{github.job}}-${{env.GODOT_BASE_BRANCH}}
          
    # Use python 3.x release (works cross platform; best to keep self contained in it's own step)
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.x'
        # Optional - x64 or x86 architecture, defaults to x64
        architecture: 'x64'

    # Setup scons, print python version and scons version info, so if anything is broken it won't run the build.
    - name: Configuring Python packages
      run: |
        python -c "import sys; print(sys.version)"
        python -m pip install scons
        python --version
        scons --version



